services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "${ELASTIC_LOCAL_PORT:-9200}:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 4G

  ollama:
    image: ollama/ollama
    ports:
      - "${OLLAMA_LOCAL_PORT:-11434}:11434"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-detective_assistant}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:5432"
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_LOCAL_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY:-SECRET_KEY}
    depends_on:
      - postgres
  
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_LOCAL_PORT:-8501}:8501"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - ollama
      - postgres
  